spring.application.name=ms-inventario
server.port=8083

# Configuracion de la base de datos H2 en memoria. Yo la uso pa mi pc nomas
spring.datasource.url=jdbc:h2:mem:inventariodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Igual que en el auth tiene que ser de 32 caracteres pra que sea segura
jwt.secret=MiClaveSuperSecretaParaLaClinicaDelDuocQueTieneQueSerLargaParaQueSeaSegura123456789