services:
  # ==========================================
  # 1. EL MOTOR DE BASE DE DATOS ÚNICO
  # ==========================================
  mysql-clinica:
    image: mysql:8.0
    container_name: mysql-clinica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_clinica_data:/var/lib/mysql

  # ==========================================
  ms-auth:
    build:
      context: ./ms-auth
    container_name: ms-auth
    restart: always
    depends_on:
      - mysql-clinica
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clinica:3306/clinica_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  ms-servicios:
    build:
      context: ./ms-servicios
    container_name: ms-servicios
    restart: always
    depends_on:
      - mysql-clinica
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clinica:3306/clinica_servicios?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  ms-profesionales:
    build:
      context: ./ms-profesionales
    container_name: ms-profesionales
    restart: always
    depends_on:
      - mysql-clinica
    ports:
      - "8092:8092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clinica:3306/clinica_profesionales?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  ms-inventario:
    build:
      context: ./ms-inventario
    container_name: ms-inventario
    restart: always
    depends_on:
      - mysql-clinica
    ports:
      - "8093:8093"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clinica:3306/clinica_inventario?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  ms-fichas:
    build:
      context: ./ms-fichas
    container_name: ms-fichas
    restart: always
    depends_on:
      - mysql-clinica
    ports:
      - "8094:8094"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clinica:3306/clinica_fichas?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  # ==========================================
  ms-paciente:
    build:
      context: ./ms.paciente
    container_name: ms-paciente
    restart: always
    depends_on:
      - mysql-clinica
    ports:
      - "8095:8095"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clinica:3306/clinica_pacientes?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  ms-usuario:
    build:
      context: ./ms.usuario
    container_name: ms-usuario
    restart: always
    depends_on:
      - mysql-clinica
    ports:
      - "8096:8096"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clinica:3306/clinica_usuarios?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  ms-agenda:
    build:
      context: ./agenda
    container_name: ms-agenda
    restart: always
    depends_on:
      - mysql-clinica
    ports:
      - "8097:8097"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clinica:3306/clinica_agenda?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  ms-consultas:
    build:
      context: ./ms.consultas
    container_name: ms-consultas
    restart: always
    depends_on:
      - mysql-clinica
    ports:
      - "8098:8098"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clinica:3306/clinica_consultas?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  ms-pagos:
    build:
      context: ./ms.pagos
    container_name: ms-pagos
    restart: always
    depends_on:
      - mysql-clinica
    ports:
      - "8099:8099"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clinica:3306/clinica_pagos?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_clinica_data: