spring.application.name=ms-fichas
server.port=8084

# Base de datos H2 en memoria para ver en el pc
spring.datasource.url=jdbc:h2:mem:fichasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# El sello de agua para cuando activemos la seguridad después
jwt.secret=MiClaveSuperSecretaParaLaClinicaDelDuocQueTieneQueSerLargaParaQueSeaSegura123456789