spring.application.name=ms-profesionales
server.port=8092
spring.profiles.active=dev

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html