spring.application.name=ms-auth
server.port=8082

# Esta es la llave maestra para firmar los tokens (¡en un trabajo real esto no se pone aquí, pero para el Duoc está perfecto!)
jwt.secret=MiClaveSuperSecretaParaLaClinicaDelDuocQueTieneQueSerLargaParaQueSeaSegura123456789

# Tiempo de vida del token (1 hora en milisegundos)
# como esta parte va en milisegundos aca ponemos eso pa qe sea una hora. 
# 1000 milisegundos = 1 segundo
# 900000 milisegundos = 15 minutos
# 1800000 milisegundos = 30 minutos
# 2700000 milisegundos = 45 minutos
# 3600000 milisegundos = 60 minutos = 1 hora
jwt.expiration=3600000