# 1. EL PUERTO (El profe pidió no usar el 8080 xq lo iba a usar en su pc)
# A este microservicio le asignamos el 8085 para que no choque con nada
server.port=8085
spring.application.name=ms-servicios

# 2. CONEXIÓN A MYSQL (El motor definitivo no es H2, es MySQL :(((( )))))
# El "?createDatabaseIfNotExist=true" es un truco de Senior para que Spring cree la base de datos solo si no existe
spring.datasource.url=jdbc:mysql://localhost:3306/clinica_servicios?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. CONFIGURACIÓN DE LAS TABLAS
# "update" hace que si agregas un campo nuevo, se actualice la tabla sin borrar los datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true